-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_thread_cnn_ctrl is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    weight_ctrls : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_image_size : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_row_size_pkg : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_window_size : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_depth : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_stride : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_replay : IN STD_LOGIC_VECTOR (16 downto 0);
    ctrl_channel : IN STD_LOGIC_VECTOR (1 downto 0);
    ctrl_row_N : IN STD_LOGIC_VECTOR (16 downto 0);
    ready : OUT STD_LOGIC_VECTOR (0 downto 0);
    ready_ap_vld : OUT STD_LOGIC;
    sc_fifo_chn_1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_1_full_n : IN STD_LOGIC;
    sc_fifo_chn_1_write : OUT STD_LOGIC;
    sc_fifo_chn_112_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    sc_fifo_chn_112_full_n : IN STD_LOGIC;
    sc_fifo_chn_112_write : OUT STD_LOGIC;
    sc_fifo_chn_113_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_113_full_n : IN STD_LOGIC;
    sc_fifo_chn_113_write : OUT STD_LOGIC;
    sc_fifo_chn_114_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_114_full_n : IN STD_LOGIC;
    sc_fifo_chn_114_write : OUT STD_LOGIC;
    sc_fifo_chn_115_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_115_full_n : IN STD_LOGIC;
    sc_fifo_chn_115_write : OUT STD_LOGIC;
    sc_fifo_chn_116_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_116_full_n : IN STD_LOGIC;
    sc_fifo_chn_116_write : OUT STD_LOGIC;
    sc_fifo_chn_117_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_117_full_n : IN STD_LOGIC;
    sc_fifo_chn_117_write : OUT STD_LOGIC;
    sc_fifo_chn_118_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    sc_fifo_chn_118_full_n : IN STD_LOGIC;
    sc_fifo_chn_118_write : OUT STD_LOGIC;
    sc_fifo_chn_119_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    sc_fifo_chn_119_full_n : IN STD_LOGIC;
    sc_fifo_chn_119_write : OUT STD_LOGIC );
end;


architecture behav of cnn_thread_cnn_ctrl is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal sc_fifo_chn_1_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal and_ln285_fu_1852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_112_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal and_ln289_fu_1931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_113_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal and_ln279_fu_1717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_114_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal and_ln280_fu_1744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_115_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln281_fu_1771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_116_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal and_ln282_fu_1798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_117_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal and_ln283_fu_1825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_118_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal and_ln287_fu_1879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sc_fifo_chn_119_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal and_ln288_fu_1904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_9_reg_1952 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal and_ln279_reg_1957 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_10_reg_1961 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal and_ln280_reg_1966 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_11_reg_1970 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal and_ln281_reg_1975 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_12_reg_1979 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal and_ln282_reg_1984 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_13_reg_1988 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state6 : BOOLEAN;
    signal and_ln283_reg_1993 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_14_reg_1997 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state7 : BOOLEAN;
    signal and_ln285_reg_2002 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_reg_2006 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal and_ln287_reg_2011 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_15_reg_2015 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_state9 : BOOLEAN;
    signal and_ln288_reg_2020 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_V_16_reg_2024 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state10 : BOOLEAN;
    signal and_ln289_reg_2029 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0647_0_reg_1600 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal p_0508_0_reg_1612 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal p_0606_0_reg_1624 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0237_0_reg_1636 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0180_0_reg_1647 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0278_0_reg_1659 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0375_0_reg_1671 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0469_0_reg_1683 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal p_0651_0_reg_1695 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal trunc_ln374_fu_1707_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_fu_1711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_1_fu_1734_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_1_fu_1738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_2_fu_1761_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_2_fu_1765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_3_fu_1788_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_3_fu_1792_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_4_fu_1815_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_4_fu_1819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_5_fu_1842_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_5_fu_1846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln378_fu_1869_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_6_fu_1873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_6_fu_1894_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_7_fu_1898_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln374_7_fu_1921_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln883_8_fu_1925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_fu_1937_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state2;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    p_0180_0_reg_1647_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0180_0_reg_1647 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0180_0_reg_1647 <= val_V_10_reg_1961;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0180_0_reg_1647 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0237_0_reg_1636_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0237_0_reg_1636 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0237_0_reg_1636 <= val_V_9_reg_1952;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0237_0_reg_1636 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0278_0_reg_1659_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0278_0_reg_1659 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0278_0_reg_1659 <= val_V_11_reg_1970;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0278_0_reg_1659 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0375_0_reg_1671_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0375_0_reg_1671 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0375_0_reg_1671 <= val_V_12_reg_1979;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0375_0_reg_1671 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0469_0_reg_1683_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0469_0_reg_1683 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0469_0_reg_1683 <= val_V_13_reg_1988;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0469_0_reg_1683 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0508_0_reg_1612_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0508_0_reg_1612 <= ap_const_lv2_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0508_0_reg_1612 <= val_V_reg_2006;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0508_0_reg_1612 <= ap_const_lv2_0;
                end if; 
            end if;
        end if;
    end process;


    p_0606_0_reg_1624_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0606_0_reg_1624 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0606_0_reg_1624 <= val_V_15_reg_2015;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0606_0_reg_1624 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0647_0_reg_1600_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0647_0_reg_1600 <= ap_const_lv17_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0647_0_reg_1600 <= val_V_14_reg_1997;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0647_0_reg_1600 <= ap_const_lv17_0;
                end if; 
            end if;
        end if;
    end process;


    p_0651_0_reg_1695_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0651_0_reg_1695 <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    p_0651_0_reg_1695 <= val_V_16_reg_2024;
                elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                    p_0651_0_reg_1695 <= ap_const_lv32_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                and_ln279_reg_1957 <= and_ln279_fu_1717_p2;
                val_V_9_reg_1952 <= ctrl_row_size_pkg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                and_ln280_reg_1966 <= and_ln280_fu_1744_p2;
                val_V_10_reg_1961 <= ctrl_window_size;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                and_ln281_reg_1975 <= and_ln281_fu_1771_p2;
                val_V_11_reg_1970 <= ctrl_depth;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                and_ln282_reg_1984 <= and_ln282_fu_1798_p2;
                val_V_12_reg_1979 <= ctrl_stride;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                and_ln283_reg_1993 <= and_ln283_fu_1825_p2;
                val_V_13_reg_1988 <= ctrl_replay;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                and_ln285_reg_2002 <= and_ln285_fu_1852_p2;
                val_V_14_reg_1997 <= weight_ctrls;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                and_ln287_reg_2011 <= and_ln287_fu_1879_p2;
                val_V_reg_2006 <= ctrl_channel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                and_ln288_reg_2020 <= and_ln288_fu_1904_p2;
                val_V_15_reg_2015 <= ctrl_row_N;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                and_ln289_reg_2029 <= and_ln289_fu_1931_p2;
                val_V_16_reg_2024 <= ctrl_image_size;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (sc_fifo_chn_1_full_n, sc_fifo_chn_112_full_n, sc_fifo_chn_113_full_n, sc_fifo_chn_114_full_n, sc_fifo_chn_115_full_n, sc_fifo_chn_116_full_n, sc_fifo_chn_117_full_n, sc_fifo_chn_118_full_n, sc_fifo_chn_119_full_n, ap_CS_fsm, ap_CS_fsm_state7, and_ln285_fu_1852_p2, ap_CS_fsm_state10, and_ln289_fu_1931_p2, ap_CS_fsm_state2, and_ln279_fu_1717_p2, ap_CS_fsm_state3, and_ln280_fu_1744_p2, ap_CS_fsm_state4, and_ln281_fu_1771_p2, ap_CS_fsm_state5, and_ln282_fu_1798_p2, ap_CS_fsm_state6, and_ln283_fu_1825_p2, ap_CS_fsm_state8, and_ln287_fu_1879_p2, ap_CS_fsm_state9, and_ln288_fu_1904_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if ((not(((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    and_ln279_fu_1717_p2 <= (trunc_ln374_fu_1707_p1 and icmp_ln883_fu_1711_p2);
    and_ln280_fu_1744_p2 <= (trunc_ln374_1_fu_1734_p1 and icmp_ln883_1_fu_1738_p2);
    and_ln281_fu_1771_p2 <= (trunc_ln374_2_fu_1761_p1 and icmp_ln883_2_fu_1765_p2);
    and_ln282_fu_1798_p2 <= (trunc_ln374_3_fu_1788_p1 and icmp_ln883_3_fu_1792_p2);
    and_ln283_fu_1825_p2 <= (trunc_ln374_4_fu_1815_p1 and icmp_ln883_4_fu_1819_p2);
    and_ln285_fu_1852_p2 <= (trunc_ln374_5_fu_1842_p1 and icmp_ln883_5_fu_1846_p2);
    and_ln287_fu_1879_p2 <= (trunc_ln378_fu_1869_p1 and icmp_ln883_6_fu_1873_p2);
    and_ln288_fu_1904_p2 <= (trunc_ln374_6_fu_1894_p1 and icmp_ln883_7_fu_1898_p2);
    and_ln289_fu_1931_p2 <= (trunc_ln374_7_fu_1921_p1 and icmp_ln883_8_fu_1925_p2);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state10_assign_proc : process(sc_fifo_chn_112_full_n, and_ln289_fu_1931_p2)
    begin
                ap_block_state10 <= ((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(sc_fifo_chn_113_full_n, and_ln279_fu_1717_p2)
    begin
                ap_block_state2 <= ((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(sc_fifo_chn_114_full_n, and_ln280_fu_1744_p2)
    begin
                ap_block_state3 <= ((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(sc_fifo_chn_115_full_n, and_ln281_fu_1771_p2)
    begin
                ap_block_state4 <= ((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(sc_fifo_chn_116_full_n, and_ln282_fu_1798_p2)
    begin
                ap_block_state5 <= ((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0));
    end process;


    ap_block_state6_assign_proc : process(sc_fifo_chn_117_full_n, and_ln283_fu_1825_p2)
    begin
                ap_block_state6 <= ((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0));
    end process;


    ap_block_state7_assign_proc : process(sc_fifo_chn_1_full_n, and_ln285_fu_1852_p2)
    begin
                ap_block_state7 <= ((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0));
    end process;


    ap_block_state8_assign_proc : process(sc_fifo_chn_118_full_n, and_ln287_fu_1879_p2)
    begin
                ap_block_state8 <= ((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0));
    end process;


    ap_block_state9_assign_proc : process(sc_fifo_chn_119_full_n, and_ln288_fu_1904_p2)
    begin
                ap_block_state9 <= ((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0));
    end process;

    icmp_ln883_1_fu_1738_p2 <= "0" when (ctrl_window_size = p_0180_0_reg_1647) else "1";
    icmp_ln883_2_fu_1765_p2 <= "0" when (ctrl_depth = p_0278_0_reg_1659) else "1";
    icmp_ln883_3_fu_1792_p2 <= "0" when (ctrl_stride = p_0375_0_reg_1671) else "1";
    icmp_ln883_4_fu_1819_p2 <= "0" when (ctrl_replay = p_0469_0_reg_1683) else "1";
    icmp_ln883_5_fu_1846_p2 <= "0" when (weight_ctrls = p_0647_0_reg_1600) else "1";
    icmp_ln883_6_fu_1873_p2 <= "0" when (ctrl_channel = p_0508_0_reg_1612) else "1";
    icmp_ln883_7_fu_1898_p2 <= "0" when (ctrl_row_N = p_0606_0_reg_1624) else "1";
    icmp_ln883_8_fu_1925_p2 <= "0" when (ctrl_image_size = p_0651_0_reg_1695) else "1";
    icmp_ln883_fu_1711_p2 <= "0" when (ctrl_row_size_pkg = p_0237_0_reg_1636) else "1";
    p_Result_8_fu_1937_p4 <= ctrl_image_size(31 downto 1);

    ready_assign_proc : process(sc_fifo_chn_1_full_n, sc_fifo_chn_112_full_n, sc_fifo_chn_113_full_n, sc_fifo_chn_114_full_n, sc_fifo_chn_115_full_n, sc_fifo_chn_116_full_n, sc_fifo_chn_117_full_n, sc_fifo_chn_118_full_n, sc_fifo_chn_119_full_n, ap_CS_fsm_state7, and_ln285_fu_1852_p2, ap_CS_fsm_state10, and_ln289_fu_1931_p2, ap_CS_fsm_state2, and_ln279_fu_1717_p2, ap_CS_fsm_state3, and_ln280_fu_1744_p2, ap_CS_fsm_state4, and_ln281_fu_1771_p2, ap_CS_fsm_state5, and_ln282_fu_1798_p2, ap_CS_fsm_state6, and_ln283_fu_1825_p2, ap_CS_fsm_state8, and_ln287_fu_1879_p2, ap_CS_fsm_state9, and_ln288_fu_1904_p2, and_ln279_reg_1957, and_ln280_reg_1966, and_ln281_reg_1975, and_ln282_reg_1984, and_ln283_reg_1993, and_ln285_reg_2002, and_ln287_reg_2011, and_ln288_reg_2020, and_ln289_reg_2029, ap_CS_fsm_state11)
    begin
        if (((not(((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln288_reg_2020) and (ap_const_logic_1 = ap_CS_fsm_state10)) or (not(((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln283_reg_1993) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((ap_const_lv1_1 = and_ln289_reg_2029) and (ap_const_logic_1 = ap_CS_fsm_state11)) or (not(((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln287_reg_2011) and (ap_const_logic_1 = ap_CS_fsm_state9)) or (not(((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln285_reg_2002) and (ap_const_logic_1 = ap_CS_fsm_state8)) or (not(((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln282_reg_1984) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln281_reg_1975) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln280_reg_1966) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln279_reg_1957) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ready <= ap_const_lv1_0;
        elsif ((not(((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ready <= ap_const_lv1_1;
        else 
            ready <= "X";
        end if; 
    end process;


    ready_ap_vld_assign_proc : process(sc_fifo_chn_1_full_n, sc_fifo_chn_112_full_n, sc_fifo_chn_113_full_n, sc_fifo_chn_114_full_n, sc_fifo_chn_115_full_n, sc_fifo_chn_116_full_n, sc_fifo_chn_117_full_n, sc_fifo_chn_118_full_n, sc_fifo_chn_119_full_n, ap_CS_fsm_state7, and_ln285_fu_1852_p2, ap_CS_fsm_state10, and_ln289_fu_1931_p2, ap_CS_fsm_state2, and_ln279_fu_1717_p2, ap_CS_fsm_state3, and_ln280_fu_1744_p2, ap_CS_fsm_state4, and_ln281_fu_1771_p2, ap_CS_fsm_state5, and_ln282_fu_1798_p2, ap_CS_fsm_state6, and_ln283_fu_1825_p2, ap_CS_fsm_state8, and_ln287_fu_1879_p2, ap_CS_fsm_state9, and_ln288_fu_1904_p2, and_ln279_reg_1957, and_ln280_reg_1966, and_ln281_reg_1975, and_ln282_reg_1984, and_ln283_reg_1993, and_ln285_reg_2002, and_ln287_reg_2011, and_ln288_reg_2020, and_ln289_reg_2029, ap_CS_fsm_state11)
    begin
        if (((not(((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln288_reg_2020) and (ap_const_logic_1 = ap_CS_fsm_state10)) or (not(((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln283_reg_1993) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((ap_const_lv1_1 = and_ln289_reg_2029) and (ap_const_logic_1 = ap_CS_fsm_state11)) or (not(((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln287_reg_2011) and (ap_const_logic_1 = ap_CS_fsm_state9)) or (not(((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln285_reg_2002) and (ap_const_logic_1 = ap_CS_fsm_state8)) or (not(((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln282_reg_1984) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln281_reg_1975) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln280_reg_1966) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln279_reg_1957) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ready_ap_vld <= ap_const_logic_1;
        else 
            ready_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_112_blk_n_assign_proc : process(sc_fifo_chn_112_full_n, ap_CS_fsm_state10, and_ln289_fu_1931_p2)
    begin
        if (((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            sc_fifo_chn_112_blk_n <= sc_fifo_chn_112_full_n;
        else 
            sc_fifo_chn_112_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_112_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_8_fu_1937_p4),32));

    sc_fifo_chn_112_write_assign_proc : process(sc_fifo_chn_112_full_n, ap_CS_fsm_state10, and_ln289_fu_1931_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln289_fu_1931_p2) and (sc_fifo_chn_112_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln289_fu_1931_p2) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            sc_fifo_chn_112_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_112_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_113_blk_n_assign_proc : process(sc_fifo_chn_113_full_n, ap_CS_fsm_state2, and_ln279_fu_1717_p2)
    begin
        if (((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            sc_fifo_chn_113_blk_n <= sc_fifo_chn_113_full_n;
        else 
            sc_fifo_chn_113_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_113_din <= ctrl_row_size_pkg(16 downto 1);

    sc_fifo_chn_113_write_assign_proc : process(sc_fifo_chn_113_full_n, ap_CS_fsm_state2, and_ln279_fu_1717_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln279_fu_1717_p2) and (sc_fifo_chn_113_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln279_fu_1717_p2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            sc_fifo_chn_113_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_113_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_114_blk_n_assign_proc : process(sc_fifo_chn_114_full_n, ap_CS_fsm_state3, and_ln280_fu_1744_p2)
    begin
        if (((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            sc_fifo_chn_114_blk_n <= sc_fifo_chn_114_full_n;
        else 
            sc_fifo_chn_114_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_114_din <= ctrl_window_size(16 downto 1);

    sc_fifo_chn_114_write_assign_proc : process(sc_fifo_chn_114_full_n, ap_CS_fsm_state3, and_ln280_fu_1744_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln280_fu_1744_p2) and (sc_fifo_chn_114_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln280_fu_1744_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            sc_fifo_chn_114_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_114_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_115_blk_n_assign_proc : process(sc_fifo_chn_115_full_n, ap_CS_fsm_state4, and_ln281_fu_1771_p2)
    begin
        if (((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            sc_fifo_chn_115_blk_n <= sc_fifo_chn_115_full_n;
        else 
            sc_fifo_chn_115_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_115_din <= ctrl_depth(16 downto 1);

    sc_fifo_chn_115_write_assign_proc : process(sc_fifo_chn_115_full_n, ap_CS_fsm_state4, and_ln281_fu_1771_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln281_fu_1771_p2) and (sc_fifo_chn_115_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln281_fu_1771_p2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            sc_fifo_chn_115_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_115_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_116_blk_n_assign_proc : process(sc_fifo_chn_116_full_n, ap_CS_fsm_state5, and_ln282_fu_1798_p2)
    begin
        if (((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            sc_fifo_chn_116_blk_n <= sc_fifo_chn_116_full_n;
        else 
            sc_fifo_chn_116_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_116_din <= ctrl_stride(16 downto 1);

    sc_fifo_chn_116_write_assign_proc : process(sc_fifo_chn_116_full_n, ap_CS_fsm_state5, and_ln282_fu_1798_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln282_fu_1798_p2) and (sc_fifo_chn_116_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln282_fu_1798_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            sc_fifo_chn_116_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_116_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_117_blk_n_assign_proc : process(sc_fifo_chn_117_full_n, ap_CS_fsm_state6, and_ln283_fu_1825_p2)
    begin
        if (((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            sc_fifo_chn_117_blk_n <= sc_fifo_chn_117_full_n;
        else 
            sc_fifo_chn_117_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_117_din <= ctrl_replay(16 downto 1);

    sc_fifo_chn_117_write_assign_proc : process(sc_fifo_chn_117_full_n, ap_CS_fsm_state6, and_ln283_fu_1825_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln283_fu_1825_p2) and (sc_fifo_chn_117_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln283_fu_1825_p2) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            sc_fifo_chn_117_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_117_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_118_blk_n_assign_proc : process(sc_fifo_chn_118_full_n, ap_CS_fsm_state8, and_ln287_fu_1879_p2)
    begin
        if (((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            sc_fifo_chn_118_blk_n <= sc_fifo_chn_118_full_n;
        else 
            sc_fifo_chn_118_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_118_din <= ctrl_channel(1 downto 1);

    sc_fifo_chn_118_write_assign_proc : process(sc_fifo_chn_118_full_n, ap_CS_fsm_state8, and_ln287_fu_1879_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln287_fu_1879_p2) and (sc_fifo_chn_118_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln287_fu_1879_p2) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            sc_fifo_chn_118_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_118_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_119_blk_n_assign_proc : process(sc_fifo_chn_119_full_n, ap_CS_fsm_state9, and_ln288_fu_1904_p2)
    begin
        if (((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            sc_fifo_chn_119_blk_n <= sc_fifo_chn_119_full_n;
        else 
            sc_fifo_chn_119_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_119_din <= ctrl_row_N(16 downto 1);

    sc_fifo_chn_119_write_assign_proc : process(sc_fifo_chn_119_full_n, ap_CS_fsm_state9, and_ln288_fu_1904_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln288_fu_1904_p2) and (sc_fifo_chn_119_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln288_fu_1904_p2) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            sc_fifo_chn_119_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_119_write <= ap_const_logic_0;
        end if; 
    end process;


    sc_fifo_chn_1_blk_n_assign_proc : process(sc_fifo_chn_1_full_n, ap_CS_fsm_state7, and_ln285_fu_1852_p2)
    begin
        if (((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            sc_fifo_chn_1_blk_n <= sc_fifo_chn_1_full_n;
        else 
            sc_fifo_chn_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sc_fifo_chn_1_din <= weight_ctrls(16 downto 1);

    sc_fifo_chn_1_write_assign_proc : process(sc_fifo_chn_1_full_n, ap_CS_fsm_state7, and_ln285_fu_1852_p2)
    begin
        if ((not(((ap_const_lv1_1 = and_ln285_fu_1852_p2) and (sc_fifo_chn_1_full_n = ap_const_logic_0))) and (ap_const_lv1_1 = and_ln285_fu_1852_p2) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            sc_fifo_chn_1_write <= ap_const_logic_1;
        else 
            sc_fifo_chn_1_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln374_1_fu_1734_p1 <= ctrl_window_size(1 - 1 downto 0);
    trunc_ln374_2_fu_1761_p1 <= ctrl_depth(1 - 1 downto 0);
    trunc_ln374_3_fu_1788_p1 <= ctrl_stride(1 - 1 downto 0);
    trunc_ln374_4_fu_1815_p1 <= ctrl_replay(1 - 1 downto 0);
    trunc_ln374_5_fu_1842_p1 <= weight_ctrls(1 - 1 downto 0);
    trunc_ln374_6_fu_1894_p1 <= ctrl_row_N(1 - 1 downto 0);
    trunc_ln374_7_fu_1921_p1 <= ctrl_image_size(1 - 1 downto 0);
    trunc_ln374_fu_1707_p1 <= ctrl_row_size_pkg(1 - 1 downto 0);
    trunc_ln378_fu_1869_p1 <= ctrl_channel(1 - 1 downto 0);
end behav;
