-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_sc_stream_last_fix_thread is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    din_0_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    din_0_empty_n : IN STD_LOGIC;
    din_0_read : OUT STD_LOGIC;
    din_1_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_1_empty_n : IN STD_LOGIC;
    din_1_read : OUT STD_LOGIC;
    din_2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    din_2_empty_n : IN STD_LOGIC;
    din_2_read : OUT STD_LOGIC;
    dout_0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    dout_0_full_n : IN STD_LOGIC;
    dout_0_write : OUT STD_LOGIC;
    dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    dout_1_full_n : IN STD_LOGIC;
    dout_1_write : OUT STD_LOGIC;
    dout_2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    dout_2_full_n : IN STD_LOGIC;
    dout_2_write : OUT STD_LOGIC );
end;


architecture behav of p_sc_stream_last_fix_thread is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal din_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal din_1_blk_n : STD_LOGIC;
    signal din_2_blk_n : STD_LOGIC;
    signal dout_0_blk_n : STD_LOGIC;
    signal grp_fu_130_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal val_tlast_V_1_reg_210 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_1_blk_n : STD_LOGIC;
    signal dout_2_blk_n : STD_LOGIC;
    signal tmp_tkeep_V_1_reg_105 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_data_V_1_reg_115 : STD_LOGIC_VECTOR (63 downto 0);
    signal io_acc_block_signal_op26 : STD_LOGIC;
    signal io_acc_block_signal_op37 : STD_LOGIC;
    signal ap_predicate_op37_write_state2 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal val_data_V_1_reg_205 : STD_LOGIC_VECTOR (63 downto 0);
    signal io_acc_block_signal_op39 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op52 : STD_LOGIC;
    signal io_acc_block_signal_op55 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal val_tkeep_V_1_reg_214 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_tlast_V_1_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_tlast_V_1_reg_219 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_predicate_tran4to5_state3 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_139_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln37_fu_147_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln_fu_151_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln182_fu_167_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1_fu_171_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state2;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_predicate_tran4to5_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln37_fu_161_p2 = ap_const_lv1_0) or (grp_fu_130_p1 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln37_fu_161_p2 = ap_const_lv1_0) or (grp_fu_130_p1 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    tmp_data_V_1_reg_115_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and ((tmp_tlast_V_1_reg_219 = ap_const_lv1_0) or (val_tlast_V_1_reg_210 = ap_const_lv1_0)))) then 
                tmp_data_V_1_reg_115 <= val_data_V_1_reg_205;
            elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln37_fu_161_p2 = ap_const_lv1_0) or (grp_fu_130_p1 = ap_const_lv1_0)))) then 
                tmp_data_V_1_reg_115 <= din_0_dout;
            end if; 
        end if;
    end process;

    tmp_tkeep_V_1_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and ((tmp_tlast_V_1_reg_219 = ap_const_lv1_0) or (val_tlast_V_1_reg_210 = ap_const_lv1_0)))) then 
                tmp_tkeep_V_1_reg_105 <= val_tkeep_V_1_reg_214;
            elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln37_fu_161_p2 = ap_const_lv1_0) or (grp_fu_130_p1 = ap_const_lv1_0)))) then 
                tmp_tkeep_V_1_reg_105 <= din_2_dout;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_tlast_V_1_reg_219 <= tmp_tlast_V_1_fu_181_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                val_data_V_1_reg_205 <= din_0_dout;
                val_tkeep_V_1_reg_214 <= din_2_dout;
                val_tlast_V_1_reg_210 <= din_1_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (din_1_dout, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, grp_fu_130_p1, icmp_ln37_fu_161_p2, ap_enable_reg_pp0_iter1, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state2 => 
                if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (icmp_ln37_fu_161_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((icmp_ln37_fu_161_p2 = ap_const_lv1_0) or (grp_fu_130_p1 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln1_fu_171_p4 <= ((grp_fu_139_p3 & ap_const_lv6_0) & trunc_ln182_fu_167_p1);
    and_ln_fu_151_p4 <= ((grp_fu_139_p3 & ap_const_lv6_0) & trunc_ln37_fu_147_p1);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op39, io_acc_block_signal_op52, io_acc_block_signal_op55)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (io_acc_block_signal_op52 = ap_const_logic_0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (io_acc_block_signal_op55 = ap_const_logic_0)))) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op39, io_acc_block_signal_op52, io_acc_block_signal_op55)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (io_acc_block_signal_op52 = ap_const_logic_0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (io_acc_block_signal_op55 = ap_const_logic_0)))) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op39, io_acc_block_signal_op52, io_acc_block_signal_op55)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (io_acc_block_signal_op52 = ap_const_logic_0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (io_acc_block_signal_op55 = ap_const_logic_0)))) or ((io_acc_block_signal_op39 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state2_assign_proc : process(io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2)
    begin
                ap_block_state2 <= ((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter0_assign_proc : process(io_acc_block_signal_op39)
    begin
                ap_block_state3_pp0_stage0_iter0 <= (io_acc_block_signal_op39 = ap_const_logic_0);
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(val_tlast_V_1_reg_210, io_acc_block_signal_op52, io_acc_block_signal_op55)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (io_acc_block_signal_op52 = ap_const_logic_0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (io_acc_block_signal_op55 = ap_const_logic_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op37_write_state2_assign_proc : process(din_1_dout, icmp_ln37_fu_161_p2)
    begin
                ap_predicate_op37_write_state2 <= ((icmp_ln37_fu_161_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1));
    end process;


    ap_predicate_tran4to5_state3_assign_proc : process(din_1_dout, tmp_tlast_V_1_fu_181_p2)
    begin
                ap_predicate_tran4to5_state3 <= ((tmp_tlast_V_1_fu_181_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1));
    end process;


    din_0_blk_n_assign_proc : process(din_0_empty_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            din_0_blk_n <= din_0_empty_n;
        else 
            din_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_0_read_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            din_0_read <= ap_const_logic_1;
        else 
            din_0_read <= ap_const_logic_0;
        end if; 
    end process;


    din_1_blk_n_assign_proc : process(din_1_empty_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            din_1_blk_n <= din_1_empty_n;
        else 
            din_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_1_read_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            din_1_read <= ap_const_logic_1;
        else 
            din_1_read <= ap_const_logic_0;
        end if; 
    end process;


    din_2_blk_n_assign_proc : process(din_2_empty_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            din_2_blk_n <= din_2_empty_n;
        else 
            din_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_2_read_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            din_2_read <= ap_const_logic_1;
        else 
            din_2_read <= ap_const_logic_0;
        end if; 
    end process;


    dout_0_blk_n_assign_proc : process(din_1_dout, dout_0_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln37_fu_161_p2, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln37_fu_161_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_0_blk_n <= dout_0_full_n;
        else 
            dout_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_0_din_assign_proc : process(din_0_dout, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, tmp_data_V_1_reg_115, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_01001)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)))) then 
            dout_0_din <= tmp_data_V_1_reg_115;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_0_din <= din_0_dout;
        else 
            dout_0_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dout_0_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_0_write <= ap_const_logic_1;
        else 
            dout_0_write <= ap_const_logic_0;
        end if; 
    end process;


    dout_1_blk_n_assign_proc : process(din_1_dout, dout_1_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln37_fu_161_p2, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln37_fu_161_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_1_blk_n <= dout_1_full_n;
        else 
            dout_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_1_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, tmp_tlast_V_1_reg_219, ap_block_pp0_stage0_01001)
    begin
        if (((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            dout_1_din <= tmp_tlast_V_1_reg_219;
        elsif (((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            dout_1_din <= ap_const_lv1_0;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_1_din <= ap_const_lv1_1;
        else 
            dout_1_din <= "X";
        end if; 
    end process;


    dout_1_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_1_write <= ap_const_logic_1;
        else 
            dout_1_write <= ap_const_logic_0;
        end if; 
    end process;


    dout_2_blk_n_assign_proc : process(din_1_dout, dout_2_full_n, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln37_fu_161_p2, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln37_fu_161_p2 = ap_const_lv1_1) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_2_blk_n <= dout_2_full_n;
        else 
            dout_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_2_din_assign_proc : process(din_2_dout, ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, tmp_tkeep_V_1_reg_105, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_01001)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)))) then 
            dout_2_din <= tmp_tkeep_V_1_reg_105;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_2_din <= din_2_dout;
        else 
            dout_2_din <= "XXXXXXXX";
        end if; 
    end process;


    dout_2_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, val_tlast_V_1_reg_210, io_acc_block_signal_op26, io_acc_block_signal_op37, ap_predicate_op37_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((val_tlast_V_1_reg_210 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((val_tlast_V_1_reg_210 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op37_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op37 = ap_const_logic_0)))) and (ap_predicate_op37_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_2_write <= ap_const_logic_1;
        else 
            dout_2_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_130_p1 <= din_1_dout;
    grp_fu_139_p3 <= din_2_dout(7 downto 7);
    icmp_ln37_fu_161_p2 <= "1" when (and_ln_fu_151_p4 = ap_const_lv8_0) else "0";
    io_acc_block_signal_op26 <= (din_2_empty_n and din_1_empty_n and din_0_empty_n);
    io_acc_block_signal_op37 <= (dout_2_full_n and dout_1_full_n and dout_0_full_n);
    io_acc_block_signal_op39 <= (din_2_empty_n and din_1_empty_n and din_0_empty_n);
    io_acc_block_signal_op52 <= (dout_2_full_n and dout_1_full_n and dout_0_full_n);
    io_acc_block_signal_op55 <= (dout_2_full_n and dout_1_full_n and dout_0_full_n);
    tmp_tlast_V_1_fu_181_p2 <= "1" when (and_ln1_fu_171_p4 = ap_const_lv8_0) else "0";
    trunc_ln182_fu_167_p1 <= din_2_dout(1 - 1 downto 0);
    trunc_ln37_fu_147_p1 <= din_2_dout(1 - 1 downto 0);
end behav;
