-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_sc_stream_resize_down_skipperinst_db_thread is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    din_0_dout : IN STD_LOGIC_VECTOR (383 downto 0);
    din_0_empty_n : IN STD_LOGIC;
    din_0_read : OUT STD_LOGIC;
    din_1_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_1_empty_n : IN STD_LOGIC;
    din_1_read : OUT STD_LOGIC;
    din_2_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    din_2_empty_n : IN STD_LOGIC;
    din_2_read : OUT STD_LOGIC;
    dout_0_din : OUT STD_LOGIC_VECTOR (383 downto 0);
    dout_0_full_n : IN STD_LOGIC;
    dout_0_write : OUT STD_LOGIC;
    dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    dout_1_full_n : IN STD_LOGIC;
    dout_1_write : OUT STD_LOGIC;
    dout_2_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    dout_2_full_n : IN STD_LOGIC;
    dout_2_write : OUT STD_LOGIC );
end;


architecture behav of p_sc_stream_resize_down_skipperinst_db_thread is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv384_lc_1 : STD_LOGIC_VECTOR (383 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";

    signal din_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal din_1_blk_n : STD_LOGIC;
    signal din_2_blk_n : STD_LOGIC;
    signal dout_0_blk_n : STD_LOGIC;
    signal val_tlast_V_fu_129_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln182_fu_137_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal and_ln50_reg_295 : STD_LOGIC_VECTOR (0 downto 0);
    signal dout_1_blk_n : STD_LOGIC;
    signal dout_2_blk_n : STD_LOGIC;
    signal bvh_d_index_reg_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_data_V_reg_267 : STD_LOGIC_VECTOR (383 downto 0);
    signal io_acc_block_signal_op26 : STD_LOGIC;
    signal io_acc_block_signal_op35 : STD_LOGIC;
    signal ap_predicate_op35_write_state2 : BOOLEAN;
    signal ap_block_state2 : BOOLEAN;
    signal val_tlast_V_reg_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal val_tkeep_V_reg_277 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Result_s_reg_290 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln50_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op63 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_184_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln308_fu_190_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln308_reg_304 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln54_fu_194_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln54_reg_309 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_tlast_V_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_tlast_V_reg_314 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal p_Result_15_fu_238_p2 : STD_LOGIC_VECTOR (383 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_Result_16_fu_261_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal trunc_ln791_fu_157_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln791_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln791_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln791_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln791_1_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_221_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln647_fu_228_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln647_fu_234_p1 : STD_LOGIC_VECTOR (383 downto 0);
    signal tmp_17_fu_244_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln647_1_fu_251_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln647_1_fu_257_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state2;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((val_tlast_V_fu_129_p1 = ap_const_lv1_0) or ((tmp_15_fu_141_p3 = ap_const_lv1_1) or (trunc_ln182_fu_137_p1 = ap_const_lv1_1))))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((val_tlast_V_fu_129_p1 = ap_const_lv1_0) or ((tmp_15_fu_141_p3 = ap_const_lv1_1) or (trunc_ln182_fu_137_p1 = ap_const_lv1_1))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    bvh_d_index_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln50_fu_178_p2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                bvh_d_index_reg_114 <= i_fu_184_p2;
            elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((val_tlast_V_fu_129_p1 = ap_const_lv1_0) or ((tmp_15_fu_141_p3 = ap_const_lv1_1) or (trunc_ln182_fu_137_p1 = ap_const_lv1_1))))) then 
                bvh_d_index_reg_114 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                and_ln50_reg_295 <= and_ln50_fu_178_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((val_tlast_V_fu_129_p1 = ap_const_lv1_0) or ((tmp_15_fu_141_p3 = ap_const_lv1_1) or (trunc_ln182_fu_137_p1 = ap_const_lv1_1))))) then
                p_Result_s_reg_290 <= din_2_dout(0 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln50_fu_178_p2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_tlast_V_reg_314 <= tmp_tlast_V_fu_216_p2;
                trunc_ln308_reg_304 <= trunc_ln308_fu_190_p1;
                trunc_ln54_reg_309 <= trunc_ln54_fu_194_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                val_data_V_reg_267 <= din_0_dout;
                val_tkeep_V_reg_277 <= din_2_dout;
                val_tlast_V_reg_272 <= din_1_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (din_1_dout, ap_CS_fsm, ap_CS_fsm_state2, val_tlast_V_fu_129_p1, trunc_ln182_fu_137_p1, tmp_15_fu_141_p3, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, and_ln50_fu_178_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state2 => 
                if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2) and ((val_tlast_V_fu_129_p1 = ap_const_lv1_0) or ((tmp_15_fu_141_p3 = ap_const_lv1_1) or (trunc_ln182_fu_137_p1 = ap_const_lv1_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (tmp_15_fu_141_p3 = ap_const_lv1_0) and (trunc_ln182_fu_137_p1 = ap_const_lv1_0) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_lv1_0 = and_ln50_fu_178_p2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_lv1_0 = and_ln50_fu_178_p2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    and_ln50_fu_178_p2 <= (icmp_ln50_fu_172_p2 and and_ln791_fu_167_p2);
    and_ln791_fu_167_p2 <= (shl_ln791_fu_161_p2 and p_Result_s_reg_290);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op63)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_const_lv1_1 = and_ln50_reg_295) and (io_acc_block_signal_op63 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op63)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_lv1_1 = and_ln50_reg_295) and (io_acc_block_signal_op63 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op63)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_lv1_1 = and_ln50_reg_295) and (io_acc_block_signal_op63 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2)
    begin
                ap_block_state2 <= ((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(and_ln50_reg_295, io_acc_block_signal_op63)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((ap_const_lv1_1 = and_ln50_reg_295) and (io_acc_block_signal_op63 = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(and_ln50_fu_178_p2)
    begin
        if ((ap_const_lv1_0 = and_ln50_fu_178_p2)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op35_write_state2_assign_proc : process(din_1_dout, trunc_ln182_fu_137_p1, tmp_15_fu_141_p3)
    begin
                ap_predicate_op35_write_state2 <= ((tmp_15_fu_141_p3 = ap_const_lv1_0) and (trunc_ln182_fu_137_p1 = ap_const_lv1_0) and (din_1_dout = ap_const_lv1_1));
    end process;


    din_0_blk_n_assign_proc : process(din_0_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            din_0_blk_n <= din_0_empty_n;
        else 
            din_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_0_read_assign_proc : process(ap_CS_fsm_state2, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2)
    begin
        if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_0_read <= ap_const_logic_1;
        else 
            din_0_read <= ap_const_logic_0;
        end if; 
    end process;


    din_1_blk_n_assign_proc : process(din_1_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            din_1_blk_n <= din_1_empty_n;
        else 
            din_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_1_read_assign_proc : process(ap_CS_fsm_state2, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2)
    begin
        if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_1_read <= ap_const_logic_1;
        else 
            din_1_read <= ap_const_logic_0;
        end if; 
    end process;


    din_2_blk_n_assign_proc : process(din_2_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            din_2_blk_n <= din_2_empty_n;
        else 
            din_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_2_read_assign_proc : process(ap_CS_fsm_state2, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2)
    begin
        if ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_2_read <= ap_const_logic_1;
        else 
            din_2_read <= ap_const_logic_0;
        end if; 
    end process;


    dout_0_blk_n_assign_proc : process(din_1_dout, dout_0_full_n, ap_CS_fsm_state2, trunc_ln182_fu_137_p1, tmp_15_fu_141_p3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln50_reg_295)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_15_fu_141_p3 = ap_const_lv1_0) and (trunc_ln182_fu_137_p1 = ap_const_lv1_0) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_0_blk_n <= dout_0_full_n;
        else 
            dout_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_0_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, p_Result_15_fu_238_p2, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            dout_0_din <= p_Result_15_fu_238_p2;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_0_din <= ap_const_lv384_lc_1;
        else 
            dout_0_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dout_0_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_0_write <= ap_const_logic_1;
        else 
            dout_0_write <= ap_const_logic_0;
        end if; 
    end process;


    dout_1_blk_n_assign_proc : process(din_1_dout, dout_1_full_n, ap_CS_fsm_state2, trunc_ln182_fu_137_p1, tmp_15_fu_141_p3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln50_reg_295)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_15_fu_141_p3 = ap_const_lv1_0) and (trunc_ln182_fu_137_p1 = ap_const_lv1_0) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_1_blk_n <= dout_1_full_n;
        else 
            dout_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_1_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, tmp_tlast_V_reg_314, ap_block_pp0_stage0_01001)
    begin
        if (((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            dout_1_din <= tmp_tlast_V_reg_314;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_1_din <= ap_const_lv1_1;
        else 
            dout_1_din <= "X";
        end if; 
    end process;


    dout_1_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_1_write <= ap_const_logic_1;
        else 
            dout_1_write <= ap_const_logic_0;
        end if; 
    end process;


    dout_2_blk_n_assign_proc : process(din_1_dout, dout_2_full_n, ap_CS_fsm_state2, trunc_ln182_fu_137_p1, tmp_15_fu_141_p3, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, and_ln50_reg_295)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_15_fu_141_p3 = ap_const_lv1_0) and (trunc_ln182_fu_137_p1 = ap_const_lv1_0) and (din_1_dout = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_2_blk_n <= dout_2_full_n;
        else 
            dout_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dout_2_din_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, ap_block_pp0_stage0_01001, p_Result_16_fu_261_p2)
    begin
        if (((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001))) then 
            dout_2_din <= p_Result_16_fu_261_p2;
        elsif ((not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            dout_2_din <= ap_const_lv48_0;
        else 
            dout_2_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dout_2_write_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, and_ln50_reg_295, io_acc_block_signal_op26, io_acc_block_signal_op35, ap_predicate_op35_write_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_lv1_1 = and_ln50_reg_295) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((io_acc_block_signal_op26 = ap_const_logic_0) or ((ap_predicate_op35_write_state2 = ap_const_boolean_1) and (io_acc_block_signal_op35 = ap_const_logic_0)))) and (ap_predicate_op35_write_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            dout_2_write <= ap_const_logic_1;
        else 
            dout_2_write <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_184_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(bvh_d_index_reg_114));
    icmp_ln50_fu_172_p2 <= "1" when (signed(bvh_d_index_reg_114) < signed(ap_const_lv32_1)) else "0";
    io_acc_block_signal_op26 <= (din_2_empty_n and din_1_empty_n and din_0_empty_n);
    io_acc_block_signal_op35 <= (dout_2_full_n and dout_1_full_n and dout_0_full_n);
    io_acc_block_signal_op63 <= (dout_2_full_n and dout_1_full_n and dout_0_full_n);
    p_Result_14_fu_210_p2 <= (shl_ln791_1_fu_204_p2 xor ap_const_lv1_1);
    p_Result_15_fu_238_p2 <= std_logic_vector(shift_right(unsigned(val_data_V_reg_267),to_integer(unsigned('0' & zext_ln647_fu_234_p1(31-1 downto 0)))));
    p_Result_16_fu_261_p2 <= std_logic_vector(shift_right(unsigned(val_tkeep_V_reg_277),to_integer(unsigned('0' & zext_ln647_1_fu_257_p1(31-1 downto 0)))));
    shl_ln791_1_fu_204_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv1_1),to_integer(unsigned('0' & xor_ln791_fu_198_p2(1-1 downto 0)))));
    shl_ln791_fu_161_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv1_1),to_integer(unsigned('0' & trunc_ln791_fu_157_p1(1-1 downto 0)))));
    sub_ln647_1_fu_251_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(tmp_17_fu_244_p3));
    sub_ln647_fu_228_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(tmp_16_fu_221_p3));
    tmp_15_fu_141_p3 <= din_2_dout(47 downto 47);
    tmp_16_fu_221_p3 <= (trunc_ln308_reg_304 & ap_const_lv7_0);
    tmp_17_fu_244_p3 <= (trunc_ln54_reg_309 & ap_const_lv4_0);
    tmp_tlast_V_fu_216_p2 <= (val_tlast_V_reg_272 and p_Result_14_fu_210_p2);
    trunc_ln182_fu_137_p1 <= din_2_dout(1 - 1 downto 0);
    trunc_ln308_fu_190_p1 <= bvh_d_index_reg_114(2 - 1 downto 0);
    trunc_ln54_fu_194_p1 <= bvh_d_index_reg_114(2 - 1 downto 0);
    trunc_ln791_fu_157_p1 <= bvh_d_index_reg_114(1 - 1 downto 0);
    val_tlast_V_fu_129_p1 <= din_1_dout;
    xor_ln791_fu_198_p2 <= (trunc_ln791_fu_157_p1 xor ap_const_lv1_1);
    zext_ln647_1_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_1_fu_251_p2),48));
    zext_ln647_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln647_fu_228_p2),384));
end behav;
