-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_sc_stream_circularlinebuffer_shift is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    din_0_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    din_0_empty_n : IN STD_LOGIC;
    din_0_read : OUT STD_LOGIC;
    din_1_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    din_1_empty_n : IN STD_LOGIC;
    din_1_read : OUT STD_LOGIC;
    din_2_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    din_2_empty_n : IN STD_LOGIC;
    din_2_read : OUT STD_LOGIC;
    din_3_dout : IN STD_LOGIC;
    din_3_empty_n : IN STD_LOGIC;
    din_3_read : OUT STD_LOGIC;
    din_4_dout : IN STD_LOGIC;
    din_4_empty_n : IN STD_LOGIC;
    din_4_read : OUT STD_LOGIC;
    din_5_dout : IN STD_LOGIC;
    din_5_empty_n : IN STD_LOGIC;
    din_5_read : OUT STD_LOGIC;
    din_6_dout : IN STD_LOGIC;
    din_6_empty_n : IN STD_LOGIC;
    din_6_read : OUT STD_LOGIC;
    din_7_dout : IN STD_LOGIC;
    din_7_empty_n : IN STD_LOGIC;
    din_7_read : OUT STD_LOGIC;
    din_8_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    din_8_empty_n : IN STD_LOGIC;
    din_8_read : OUT STD_LOGIC;
    din_9_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    din_9_empty_n : IN STD_LOGIC;
    din_9_read : OUT STD_LOGIC;
    dout_0_din : OUT STD_LOGIC_VECTOR (383 downto 0);
    dout_0_full_n : IN STD_LOGIC;
    dout_0_write : OUT STD_LOGIC;
    dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    dout_1_full_n : IN STD_LOGIC;
    dout_1_write : OUT STD_LOGIC;
    dout_2_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    dout_2_full_n : IN STD_LOGIC;
    dout_2_write : OUT STD_LOGIC;
    ctrl_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_0_empty_n : IN STD_LOGIC;
    ctrl_0_read : OUT STD_LOGIC;
    ctrl_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_1_empty_n : IN STD_LOGIC;
    ctrl_1_read : OUT STD_LOGIC;
    ctrl_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_2_empty_n : IN STD_LOGIC;
    ctrl_2_read : OUT STD_LOGIC;
    ctrl_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_3_empty_n : IN STD_LOGIC;
    ctrl_3_read : OUT STD_LOGIC;
    ctrl_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_4_empty_n : IN STD_LOGIC;
    ctrl_4_read : OUT STD_LOGIC;
    ctrl_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_5_empty_n : IN STD_LOGIC;
    ctrl_5_read : OUT STD_LOGIC;
    ctrl_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ctrl_6_empty_n : IN STD_LOGIC;
    ctrl_6_read : OUT STD_LOGIC;
    ctrl_7_dout : IN STD_LOGIC;
    ctrl_7_empty_n : IN STD_LOGIC;
    ctrl_7_read : OUT STD_LOGIC;
    count_out : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of p_sc_stream_circularlinebuffer_shift is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "p_sc_stream_circularlinebuffer_shift,hls_ip_2019_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.274000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=3504,HLS_SYN_LUT=2541,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_0_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_1_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_2_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_3_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_4_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_5_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_6_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_7_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_8_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_9_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_din : STD_LOGIC_VECTOR (383 downto 0);
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_write : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_write : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_write : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_0_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_1_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_2_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_3_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_4_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_5_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_6_read : STD_LOGIC;
    signal grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_7_read : STD_LOGIC;

    component p_sc_stream_circularlinebuffer_shift_thread_shift IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        din_0_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        din_0_empty_n : IN STD_LOGIC;
        din_0_read : OUT STD_LOGIC;
        din_1_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        din_1_empty_n : IN STD_LOGIC;
        din_1_read : OUT STD_LOGIC;
        din_2_dout : IN STD_LOGIC_VECTOR (127 downto 0);
        din_2_empty_n : IN STD_LOGIC;
        din_2_read : OUT STD_LOGIC;
        din_3_dout : IN STD_LOGIC;
        din_3_empty_n : IN STD_LOGIC;
        din_3_read : OUT STD_LOGIC;
        din_4_dout : IN STD_LOGIC;
        din_4_empty_n : IN STD_LOGIC;
        din_4_read : OUT STD_LOGIC;
        din_5_dout : IN STD_LOGIC;
        din_5_empty_n : IN STD_LOGIC;
        din_5_read : OUT STD_LOGIC;
        din_6_dout : IN STD_LOGIC;
        din_6_empty_n : IN STD_LOGIC;
        din_6_read : OUT STD_LOGIC;
        din_7_dout : IN STD_LOGIC;
        din_7_empty_n : IN STD_LOGIC;
        din_7_read : OUT STD_LOGIC;
        din_8_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        din_8_empty_n : IN STD_LOGIC;
        din_8_read : OUT STD_LOGIC;
        din_9_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        din_9_empty_n : IN STD_LOGIC;
        din_9_read : OUT STD_LOGIC;
        dout_0_din : OUT STD_LOGIC_VECTOR (383 downto 0);
        dout_0_full_n : IN STD_LOGIC;
        dout_0_write : OUT STD_LOGIC;
        dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        dout_1_full_n : IN STD_LOGIC;
        dout_1_write : OUT STD_LOGIC;
        dout_2_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        dout_2_full_n : IN STD_LOGIC;
        dout_2_write : OUT STD_LOGIC;
        ctrl_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_0_empty_n : IN STD_LOGIC;
        ctrl_0_read : OUT STD_LOGIC;
        ctrl_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_1_empty_n : IN STD_LOGIC;
        ctrl_1_read : OUT STD_LOGIC;
        ctrl_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_2_empty_n : IN STD_LOGIC;
        ctrl_2_read : OUT STD_LOGIC;
        ctrl_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_3_empty_n : IN STD_LOGIC;
        ctrl_3_read : OUT STD_LOGIC;
        ctrl_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_4_empty_n : IN STD_LOGIC;
        ctrl_4_read : OUT STD_LOGIC;
        ctrl_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_5_empty_n : IN STD_LOGIC;
        ctrl_5_read : OUT STD_LOGIC;
        ctrl_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ctrl_6_empty_n : IN STD_LOGIC;
        ctrl_6_read : OUT STD_LOGIC;
        ctrl_7_dout : IN STD_LOGIC;
        ctrl_7_empty_n : IN STD_LOGIC;
        ctrl_7_read : OUT STD_LOGIC );
    end component;



begin
    grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106 : component p_sc_stream_circularlinebuffer_shift_thread_shift
    port map (
        ap_clk => clk,
        ap_rst => reset,
        din_0_dout => din_0_dout,
        din_0_empty_n => din_0_empty_n,
        din_0_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_0_read,
        din_1_dout => din_1_dout,
        din_1_empty_n => din_1_empty_n,
        din_1_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_1_read,
        din_2_dout => din_2_dout,
        din_2_empty_n => din_2_empty_n,
        din_2_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_2_read,
        din_3_dout => din_3_dout,
        din_3_empty_n => din_3_empty_n,
        din_3_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_3_read,
        din_4_dout => din_4_dout,
        din_4_empty_n => din_4_empty_n,
        din_4_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_4_read,
        din_5_dout => din_5_dout,
        din_5_empty_n => din_5_empty_n,
        din_5_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_5_read,
        din_6_dout => din_6_dout,
        din_6_empty_n => din_6_empty_n,
        din_6_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_6_read,
        din_7_dout => din_7_dout,
        din_7_empty_n => din_7_empty_n,
        din_7_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_7_read,
        din_8_dout => din_8_dout,
        din_8_empty_n => din_8_empty_n,
        din_8_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_8_read,
        din_9_dout => din_9_dout,
        din_9_empty_n => din_9_empty_n,
        din_9_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_9_read,
        dout_0_din => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_din,
        dout_0_full_n => dout_0_full_n,
        dout_0_write => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_write,
        dout_1_din => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_din,
        dout_1_full_n => dout_1_full_n,
        dout_1_write => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_write,
        dout_2_din => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_din,
        dout_2_full_n => dout_2_full_n,
        dout_2_write => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_write,
        ctrl_0_dout => ctrl_0_dout,
        ctrl_0_empty_n => ctrl_0_empty_n,
        ctrl_0_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_0_read,
        ctrl_1_dout => ctrl_1_dout,
        ctrl_1_empty_n => ctrl_1_empty_n,
        ctrl_1_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_1_read,
        ctrl_2_dout => ctrl_2_dout,
        ctrl_2_empty_n => ctrl_2_empty_n,
        ctrl_2_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_2_read,
        ctrl_3_dout => ctrl_3_dout,
        ctrl_3_empty_n => ctrl_3_empty_n,
        ctrl_3_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_3_read,
        ctrl_4_dout => ctrl_4_dout,
        ctrl_4_empty_n => ctrl_4_empty_n,
        ctrl_4_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_4_read,
        ctrl_5_dout => ctrl_5_dout,
        ctrl_5_empty_n => ctrl_5_empty_n,
        ctrl_5_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_5_read,
        ctrl_6_dout => ctrl_6_dout,
        ctrl_6_empty_n => ctrl_6_empty_n,
        ctrl_6_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_6_read,
        ctrl_7_dout => ctrl_7_dout,
        ctrl_7_empty_n => ctrl_7_empty_n,
        ctrl_7_read => grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_7_read);




    count_out <= ap_const_lv32_0;
    ctrl_0_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_0_read;
    ctrl_1_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_1_read;
    ctrl_2_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_2_read;
    ctrl_3_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_3_read;
    ctrl_4_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_4_read;
    ctrl_5_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_5_read;
    ctrl_6_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_6_read;
    ctrl_7_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_ctrl_7_read;
    din_0_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_0_read;
    din_1_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_1_read;
    din_2_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_2_read;
    din_3_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_3_read;
    din_4_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_4_read;
    din_5_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_5_read;
    din_6_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_6_read;
    din_7_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_7_read;
    din_8_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_8_read;
    din_9_read <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_din_9_read;
    dout_0_din <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_din;
    dout_0_write <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_0_write;
    dout_1_din <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_din;
    dout_1_write <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_1_write;
    dout_2_din <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_din;
    dout_2_write <= grp_p_sc_stream_circularlinebuffer_shift_thread_shift_fu_106_dout_2_write;
end behav;
