-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_sc_stream_merge_raw is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    din_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_0_empty_n : IN STD_LOGIC;
    din_0_read : OUT STD_LOGIC;
    din_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_1_empty_n : IN STD_LOGIC;
    din_1_read : OUT STD_LOGIC;
    din_2_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_2_empty_n : IN STD_LOGIC;
    din_2_read : OUT STD_LOGIC;
    din_3_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_3_empty_n : IN STD_LOGIC;
    din_3_read : OUT STD_LOGIC;
    din_4_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_4_empty_n : IN STD_LOGIC;
    din_4_read : OUT STD_LOGIC;
    din_5_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_5_empty_n : IN STD_LOGIC;
    din_5_read : OUT STD_LOGIC;
    din_6_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_6_empty_n : IN STD_LOGIC;
    din_6_read : OUT STD_LOGIC;
    din_7_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_7_empty_n : IN STD_LOGIC;
    din_7_read : OUT STD_LOGIC;
    din_8_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_8_empty_n : IN STD_LOGIC;
    din_8_read : OUT STD_LOGIC;
    din_9_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_9_empty_n : IN STD_LOGIC;
    din_9_read : OUT STD_LOGIC;
    din_10_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_10_empty_n : IN STD_LOGIC;
    din_10_read : OUT STD_LOGIC;
    din_11_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_11_empty_n : IN STD_LOGIC;
    din_11_read : OUT STD_LOGIC;
    din_12_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_12_empty_n : IN STD_LOGIC;
    din_12_read : OUT STD_LOGIC;
    din_13_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_13_empty_n : IN STD_LOGIC;
    din_13_read : OUT STD_LOGIC;
    din_14_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_14_empty_n : IN STD_LOGIC;
    din_14_read : OUT STD_LOGIC;
    din_15_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    din_15_empty_n : IN STD_LOGIC;
    din_15_read : OUT STD_LOGIC;
    din_16_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_16_empty_n : IN STD_LOGIC;
    din_16_read : OUT STD_LOGIC;
    din_17_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_17_empty_n : IN STD_LOGIC;
    din_17_read : OUT STD_LOGIC;
    din_18_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_18_empty_n : IN STD_LOGIC;
    din_18_read : OUT STD_LOGIC;
    din_19_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_19_empty_n : IN STD_LOGIC;
    din_19_read : OUT STD_LOGIC;
    din_20_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_20_empty_n : IN STD_LOGIC;
    din_20_read : OUT STD_LOGIC;
    din_21_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_21_empty_n : IN STD_LOGIC;
    din_21_read : OUT STD_LOGIC;
    din_22_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_22_empty_n : IN STD_LOGIC;
    din_22_read : OUT STD_LOGIC;
    din_23_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    din_23_empty_n : IN STD_LOGIC;
    din_23_read : OUT STD_LOGIC;
    dout_0_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    dout_0_full_n : IN STD_LOGIC;
    dout_0_write : OUT STD_LOGIC;
    dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    dout_1_full_n : IN STD_LOGIC;
    dout_1_write : OUT STD_LOGIC;
    dout_2_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    dout_2_full_n : IN STD_LOGIC;
    dout_2_write : OUT STD_LOGIC );
end;


architecture behav of p_sc_stream_merge_raw is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "p_sc_stream_merge_raw,hls_ip_2019_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.351750,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1452,HLS_SYN_LUT=532,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_0_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_1_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_2_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_3_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_4_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_5_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_6_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_7_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_8_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_9_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_10_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_11_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_12_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_13_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_14_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_15_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_16_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_17_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_18_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_19_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_20_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_21_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_22_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_23_read : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_write : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_write : STD_LOGIC;
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_write : STD_LOGIC;

    component p_sc_stream_merge_raw_thread_sc_stream_merge_raw IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        din_0_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_0_empty_n : IN STD_LOGIC;
        din_0_read : OUT STD_LOGIC;
        din_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_1_empty_n : IN STD_LOGIC;
        din_1_read : OUT STD_LOGIC;
        din_2_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_2_empty_n : IN STD_LOGIC;
        din_2_read : OUT STD_LOGIC;
        din_3_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_3_empty_n : IN STD_LOGIC;
        din_3_read : OUT STD_LOGIC;
        din_4_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_4_empty_n : IN STD_LOGIC;
        din_4_read : OUT STD_LOGIC;
        din_5_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_5_empty_n : IN STD_LOGIC;
        din_5_read : OUT STD_LOGIC;
        din_6_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_6_empty_n : IN STD_LOGIC;
        din_6_read : OUT STD_LOGIC;
        din_7_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        din_7_empty_n : IN STD_LOGIC;
        din_7_read : OUT STD_LOGIC;
        din_8_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_8_empty_n : IN STD_LOGIC;
        din_8_read : OUT STD_LOGIC;
        din_9_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_9_empty_n : IN STD_LOGIC;
        din_9_read : OUT STD_LOGIC;
        din_10_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_10_empty_n : IN STD_LOGIC;
        din_10_read : OUT STD_LOGIC;
        din_11_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_11_empty_n : IN STD_LOGIC;
        din_11_read : OUT STD_LOGIC;
        din_12_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_12_empty_n : IN STD_LOGIC;
        din_12_read : OUT STD_LOGIC;
        din_13_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_13_empty_n : IN STD_LOGIC;
        din_13_read : OUT STD_LOGIC;
        din_14_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_14_empty_n : IN STD_LOGIC;
        din_14_read : OUT STD_LOGIC;
        din_15_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        din_15_empty_n : IN STD_LOGIC;
        din_15_read : OUT STD_LOGIC;
        din_16_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_16_empty_n : IN STD_LOGIC;
        din_16_read : OUT STD_LOGIC;
        din_17_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_17_empty_n : IN STD_LOGIC;
        din_17_read : OUT STD_LOGIC;
        din_18_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_18_empty_n : IN STD_LOGIC;
        din_18_read : OUT STD_LOGIC;
        din_19_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_19_empty_n : IN STD_LOGIC;
        din_19_read : OUT STD_LOGIC;
        din_20_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_20_empty_n : IN STD_LOGIC;
        din_20_read : OUT STD_LOGIC;
        din_21_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_21_empty_n : IN STD_LOGIC;
        din_21_read : OUT STD_LOGIC;
        din_22_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_22_empty_n : IN STD_LOGIC;
        din_22_read : OUT STD_LOGIC;
        din_23_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        din_23_empty_n : IN STD_LOGIC;
        din_23_read : OUT STD_LOGIC;
        dout_0_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        dout_0_full_n : IN STD_LOGIC;
        dout_0_write : OUT STD_LOGIC;
        dout_1_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        dout_1_full_n : IN STD_LOGIC;
        dout_1_write : OUT STD_LOGIC;
        dout_2_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        dout_2_full_n : IN STD_LOGIC;
        dout_2_write : OUT STD_LOGIC );
    end component;



begin
    grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108 : component p_sc_stream_merge_raw_thread_sc_stream_merge_raw
    port map (
        ap_clk => clk,
        ap_rst => reset,
        din_0_dout => din_0_dout,
        din_0_empty_n => din_0_empty_n,
        din_0_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_0_read,
        din_1_dout => din_1_dout,
        din_1_empty_n => din_1_empty_n,
        din_1_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_1_read,
        din_2_dout => din_2_dout,
        din_2_empty_n => din_2_empty_n,
        din_2_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_2_read,
        din_3_dout => din_3_dout,
        din_3_empty_n => din_3_empty_n,
        din_3_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_3_read,
        din_4_dout => din_4_dout,
        din_4_empty_n => din_4_empty_n,
        din_4_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_4_read,
        din_5_dout => din_5_dout,
        din_5_empty_n => din_5_empty_n,
        din_5_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_5_read,
        din_6_dout => din_6_dout,
        din_6_empty_n => din_6_empty_n,
        din_6_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_6_read,
        din_7_dout => din_7_dout,
        din_7_empty_n => din_7_empty_n,
        din_7_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_7_read,
        din_8_dout => din_8_dout,
        din_8_empty_n => din_8_empty_n,
        din_8_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_8_read,
        din_9_dout => din_9_dout,
        din_9_empty_n => din_9_empty_n,
        din_9_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_9_read,
        din_10_dout => din_10_dout,
        din_10_empty_n => din_10_empty_n,
        din_10_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_10_read,
        din_11_dout => din_11_dout,
        din_11_empty_n => din_11_empty_n,
        din_11_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_11_read,
        din_12_dout => din_12_dout,
        din_12_empty_n => din_12_empty_n,
        din_12_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_12_read,
        din_13_dout => din_13_dout,
        din_13_empty_n => din_13_empty_n,
        din_13_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_13_read,
        din_14_dout => din_14_dout,
        din_14_empty_n => din_14_empty_n,
        din_14_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_14_read,
        din_15_dout => din_15_dout,
        din_15_empty_n => din_15_empty_n,
        din_15_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_15_read,
        din_16_dout => din_16_dout,
        din_16_empty_n => din_16_empty_n,
        din_16_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_16_read,
        din_17_dout => din_17_dout,
        din_17_empty_n => din_17_empty_n,
        din_17_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_17_read,
        din_18_dout => din_18_dout,
        din_18_empty_n => din_18_empty_n,
        din_18_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_18_read,
        din_19_dout => din_19_dout,
        din_19_empty_n => din_19_empty_n,
        din_19_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_19_read,
        din_20_dout => din_20_dout,
        din_20_empty_n => din_20_empty_n,
        din_20_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_20_read,
        din_21_dout => din_21_dout,
        din_21_empty_n => din_21_empty_n,
        din_21_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_21_read,
        din_22_dout => din_22_dout,
        din_22_empty_n => din_22_empty_n,
        din_22_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_22_read,
        din_23_dout => din_23_dout,
        din_23_empty_n => din_23_empty_n,
        din_23_read => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_23_read,
        dout_0_din => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_din,
        dout_0_full_n => dout_0_full_n,
        dout_0_write => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_write,
        dout_1_din => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_din,
        dout_1_full_n => dout_1_full_n,
        dout_1_write => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_write,
        dout_2_din => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_din,
        dout_2_full_n => dout_2_full_n,
        dout_2_write => grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_write);




    din_0_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_0_read;
    din_10_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_10_read;
    din_11_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_11_read;
    din_12_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_12_read;
    din_13_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_13_read;
    din_14_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_14_read;
    din_15_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_15_read;
    din_16_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_16_read;
    din_17_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_17_read;
    din_18_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_18_read;
    din_19_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_19_read;
    din_1_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_1_read;
    din_20_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_20_read;
    din_21_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_21_read;
    din_22_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_22_read;
    din_23_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_23_read;
    din_2_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_2_read;
    din_3_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_3_read;
    din_4_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_4_read;
    din_5_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_5_read;
    din_6_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_6_read;
    din_7_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_7_read;
    din_8_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_8_read;
    din_9_read <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_din_9_read;
    dout_0_din <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_din;
    dout_0_write <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_0_write;
    dout_1_din <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_din;
    dout_1_write <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_1_write;
    dout_2_din <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_din;
    dout_2_write <= grp_p_sc_stream_merge_raw_thread_sc_stream_merge_raw_fu_108_dout_2_write;
end behav;
