-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sc_status_reg is
port (
    clk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    status : IN STD_LOGIC_VECTOR (31 downto 0);
    ingress_out_0 : IN STD_LOGIC_VECTOR (7 downto 0);
    ingress_out_1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ingress_out_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    ingress_in : OUT STD_LOGIC_VECTOR (31 downto 0);
    egress_out_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    egress_out_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    egress_out_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    egress_in : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sc_status_reg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sc_status_reg,hls_ip_2019_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.611000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=41,HLS_VERSION=2019_1}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal sc_status_reg_ssd_1_load_fu_130_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_0_ap_vld : STD_LOGIC;
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_1_ap_vld : STD_LOGIC;
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_2_ap_vld : STD_LOGIC;
    signal call_ln89_sc_status_reg_met_in_handle_fu_100_ingress_in : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ln89_sc_status_reg_met_in_handle_fu_100_ingress_in_ap_vld : STD_LOGIC;
    signal sc_status_reg_ssd_load_fu_126_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component sc_status_reg_met_out_handle IS
    port (
        status : IN STD_LOGIC_VECTOR (31 downto 0);
        ingress_out_0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ingress_out_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ingress_out_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        egress_out_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        egress_out_0_ap_vld : OUT STD_LOGIC;
        egress_out_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        egress_out_1_ap_vld : OUT STD_LOGIC;
        egress_out_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        egress_out_2_ap_vld : OUT STD_LOGIC );
    end component;


    component sc_status_reg_met_in_handle IS
    port (
        ingress_in : OUT STD_LOGIC_VECTOR (31 downto 0);
        ingress_in_ap_vld : OUT STD_LOGIC;
        egress_in : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    call_ln85_sc_status_reg_met_out_handle_fu_74 : component sc_status_reg_met_out_handle
    port map (
        status => status,
        ingress_out_0 => ingress_out_0,
        ingress_out_1 => ingress_out_1,
        ingress_out_2 => ingress_out_2,
        egress_out_0 => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_0,
        egress_out_0_ap_vld => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_0_ap_vld,
        egress_out_1 => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_1,
        egress_out_1_ap_vld => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_1_ap_vld,
        egress_out_2 => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_2,
        egress_out_2_ap_vld => call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_2_ap_vld);

    call_ln89_sc_status_reg_met_in_handle_fu_100 : component sc_status_reg_met_in_handle
    port map (
        ingress_in => call_ln89_sc_status_reg_met_in_handle_fu_100_ingress_in,
        ingress_in_ap_vld => call_ln89_sc_status_reg_met_in_handle_fu_100_ingress_in_ap_vld,
        egress_in => egress_in);




    egress_out_0 <= call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_0;
    egress_out_1 <= call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_1;
    egress_out_2 <= call_ln85_sc_status_reg_met_out_handle_fu_74_egress_out_2;
    ingress_in <= call_ln89_sc_status_reg_met_in_handle_fu_100_ingress_in;
    sc_status_reg_ssd_1_load_fu_130_p1 <= ap_const_lv1_0;
    sc_status_reg_ssd_load_fu_126_p1 <= ap_const_lv1_0;
end behav;
