#!/bin/bash
#https://yosefk.com/blog/passing-shell-script-arguments-to-a-subprocess.html
args=
for arg in "$@";
do
  args="$args '$arg'"
done


USER_LOGIN=jonathan
USER=thinker
REMOTE=schougaard.ddns.net
PORT=5000
PWD_TMP=${PWD}
CMD="/bin/bash $args"
#echo ${CMD}
#exit
#echo connect
ssh -p 5000 thinker@schougaard.ddns.net -R 10000:localhost:22 "mkdir -p share/${USER_LOGIN} && sshfs -p 10000 ${USER_LOGIN}@localhost: share/${USER_LOGIN};HOME_TMP=\$HOME; HOME=share/${USER_LOGIN}; cd; ${CMD}; RETVALUE=\$?; cd \$HOME_TMP; fusermount -u share/${USER_LOGIN}; exit \$RETVALUE"


